from .repair_strategy_form_widget import RepairStrategyFormWidget
from .logs_widget import LogsWidget
from .separator_widget import SeparatorWidget
from .settings_dialog_widget import SettingsDialogWidget
from .keybindings_form_widget import KeybindingsFormWidget
